# see docs: https://prettier.io/docs/en/configuration.html

# prettier config
printWidth: 100
tabWidth: 2
useTabs: false
singleQuote: true
semi: true
endOfLine: 'auto'
arrowParens: 'avoid'
trailingComma: 'none'
